### ISSUE TITLE
multi-line imports including both normal imports and flow types are broken

### ISSUE THREAD

**Issue by jrnail23** [davidmfoley/node-trucker#14]
As of Flow v0.38, the following syntax is now supported:

```js
import MyModule, {type FlowTypeA, type FlowTypeB} from './MyModule'
```

unfortunately, when that spans more than one line (as below), Trucker incorrectly applies path fixes when moving files.

```js
import MyModule, {
  type FlowTypeA,
  type FlowTypeB
} from './MyModule'
```

I'll follow up with a failing test case when I have a free moment.

**Comment by davidmfoley** [comment]
Awesome; didn't even realize that syntax existed.

**Comment by davidmfoley** [comment]
I think this has been fixed by upgrading the version of the parser library used to parse javascript files. Please let me know if you have any more problems.
