### ISSUE TITLE
doesn't work with NODE_PATH

### ISSUE THREAD

**Issue by oprogramador** [davidmfoley/node-trucker#18]
in my project I have imports like:
```js
import MyCustomError from 'my-project/error/my-custom-error'
```
and I have `NODE_PATH` env with the real path to my project;
unfortunately `trucker` treats files imported in this way as unused

**Comment by davidmfoley** [comment]
Great catch. I didn't think of this. Thanks.

**Comment by davidmfoley** [comment]
Would you mind retesting with the latest version? I think I may have fixed this as a side-effect of using `require.resolve` a couple of version ago.
