### ISSUE TITLE
Breaks when you have symlinks pointing to a folder, and both are in scope

### ISSUE THREAD

**Issue by eedrah** [davidmfoley/node-trucker#19]
Apologies, I know this is super convoluted. But I wanted to write it down anyway for completeness. Please close this issue if you like, because I feel it's not exactly a high priority.

# The Issue

If you have the following file structure (for example):

```
components/
├── c
│   ├── EditProject.js
│   └── ViewProject.js
├── container -> c
├── p
│   ├── Button.js
│   └── presentationLayer
│       └── ViewProject.js
└── presentational -> p
```
If you try and move `Button.js` into the folder `presentationLayer`, then the imports break. It appears to be a conflict between the naming of the symlink and the folder, as it looks like they write over each other, without deleting the rest of the line the other operation wrote. For example, when I moved `ViewProject.js` into `presentationLayer` from its parent, I got the following:

```js
import ViewProject from '../p/presentationLayer/ViewProjectnLayer/ViewProject'
```

# Resolution

I don't think this is something that this project should solve, as it is a rare structure, and it would be a shame to treat symlinks as different to folders in other ways. I'm writing this here in case someone else wants to read it to provide insight into their own problems, but I'm recommending this be closed immediately.

**Comment by davidmfoley** [comment]
Interesting. Thanks for the report.
