### ISSUE TITLE
Files got converted from UTF-8 to Binary

### ISSUE THREAD

**Issue by JonFranchi** [davidmfoley/node-trucker#26]
I really like this tool and was saving lot's of time by reorganizing a legacy repo and removing some cruff, but then when I pushed changes I discovered GIT was recognizing a bunch of files as Binary now which had previously been UTF-8.

```
| => git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
________________________________________________________________________________
| => file -I ./services/iam/v0/templates/template1.js
./services/iam/v0/templates/template1.js: text/x-java; charset=utf-8
________________________________________________________________________________
| => git checkout the-branch
Switched to branch 'the-branch'
________________________________________________________________________________
| => file -I ./services/email/legacy/templates/template1.js
./services/email/legacy/templates/template1.js: application/octet-stream; charset=binary
```

I can't share the exact files, but they are all node JS files with some html mixed in.  I had one more where `you'll` was converted to `youb ll`.

**Comment by davidmfoley** [comment]
Thanks for the report. What OS are you using?

**Comment by JonFranchi** [comment]
Sorry, this is not an amazingly detailed report. 

Using MacOS.  We found this happened specifically with email template files where the dev who created them ages ago thinks he copy/pasted some rich text directly in and it seems it didn't handle the fancy apostrophe.

Maybe it would be helpful to get warnings if something like this is unparseable? Or if character encoding will change?  I am admittedly not that knowledgeable on the wide world of character encoding.

**Comment by davidmfoley** [comment]
Perhaps a command-line switch for fallback encoding might be a good compromise here (and exiting non-zero if the fallback is not set and a file with unknown encoding is encountered).

**Comment by eedrah** [comment]
Thanks for Trucker, David - it's great!

I can confirm this issue - it's incorrectly changing some UTF-8 encodings when it touches a file. Here are some reproduction instructions:

```
mkdir /tmp/trucker-repro
cd /tmp/trucker-repro/
echo 'export default "I’m a close quote character"' > thing.js
cat thing.js
hexdump -C thing.js
trucker thing.js other-thing.js
cat other-thing.js
hexdump -C other-thing.js
```

And we can see that the close quote UTF-8 character has changed by looking at the `cat`ed or `hexdump`ed files:

```
hexdump -C thing.js
00000000  65 78 70 6f 72 74 20 64  65 66 61 75 6c 74 20 22  |export default "|
00000010  49 e2 80 99 6d 20 61 20  63 6c 6f 73 65 20 71 75  |I...m a close qu|
00000020  6f 74 65 20 63 68 61 72  61 63 74 65 72 22 0a     |ote character".|
0000002f
```

```
hexdump -C other-thing.js
00000000  65 78 70 6f 72 74 20 64  65 66 61 75 6c 74 20 22  |export default "|
00000010  49 62 00 19 6d 20 61 20  63 6c 6f 73 65 20 71 75  |Ib..m a close qu|
00000020  6f 74 65 20 63 68 61 72  61 63 74 65 72 22 0a     |ote character".|
0000002f
```

**Comment by eedrah** [comment]
In my simple example this error is taking place in the export, but notice it also does it if it's in another part of the file that is completely unrelated to importing or exporting

**Comment by davidmfoley** [comment]
I finally got around to fixing this in v1.0.0
