### ISSUE TITLE
Fails to run, complains about missing `./lib`

### ISSUE THREAD

**Issue by datenreisender** [davidmfoley/node-trucker#32]
When I try to run it (either through `npx trucker`, which is my preferred way, or after doing `npm install -g trucker`) I get an error complaining about a missing `./lib`. 

```
➜ npx trucker
npx: installed 11 in 2.787s
Cannot find module './lib'
```

**Comment by davidmfoley** [comment]
Ugh; I missed the `"files"` changes needed when porting to typescript. Fixed in 1.0.4. Thanks for the report!
