### ISSUE TITLE
Support JSX / CJSX

### ISSUE THREAD

**Issue by rapilabs** [davidmfoley/node-trucker#4]
Nice tool, although this is probably the 1 time I wished that regexes were used rather than actually parsing the code as it would mean I'd be able to process JSX :)

**Comment by davidmfoley** [comment]
This might be an option https://github.com/RReverser/acorn-jsx

**Comment by davidmfoley** [comment]
Trucker v0.4 uses babel and should be able to deal with ES6 and JSX - let me know if you give it a try and have problems. CJSX is not supported.
